server:
  port: 8080
#spring:
#  redis:
#    database: 0
#    host: 172.16.117.150
#    port: 6379
#    password: 123
#    jedis:
#      pool:
#        max-active: 8
#        max-idle: 8
#        max-wait: -1ms
#        min-idle: 0
